# Generated by Django 4.2.4 on 2023-10-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_admin', 'Is Admin')]},
        ),
    ]
