# Generated by Django 4.2.4 on 2023-10-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
