# Generated by Django 4.2.4 on 2023-10-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
