# Generated by Django 4.2.4 on 2023-10-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_userprofile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
