# Generated by Django 4.2.4 on 2023-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_fullname_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
