# Generated by Django 4.2.4 on 2023-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_userprofile_full_name_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
