# Generated by Django 4.2.4 on 2023-10-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
