# Generated by Django 4.2.4 on 2023-10-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_post_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_at',
        ),
    ]
