# Generated by Django 4.2.4 on 2023-10-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_like_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
