# Generated by Django 4.2.4 on 2023-10-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
