# Generated by Django 4.2.4 on 2023-10-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
