# Generated by Django 4.2.4 on 2023-10-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
