# Generated by Django 4.2.4 on 2023-10-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
