# Generated by Django 4.2.4 on 2023-10-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0060_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
