# Generated by Django 4.2.4 on 2023-10-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0062_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
