# Generated by Django 4.2.4 on 2023-10-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
