# Generated by Django 4.2.4 on 2023-10-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
