# Generated by Django 4.2.4 on 2023-10-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0070_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
    ]
