# Generated by Django 4.2.4 on 2023-10-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0072_rename_comment_text_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
