# Generated by Django 4.2.4 on 2023-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0074_follower_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
