# Generated by Django 4.2.4 on 2023-10-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0078_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
